import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * One sidebar per top navbar section. Structure inside each section comes from
 * `docs/<section>/` via autogenerated slices. See:
 * https://docusaurus.io/docs/sidebar/multiple-sidebars
 */
const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "overview" }],
  guides: [{ type: "autogenerated", dirName: "guides" }],
  spec: [{ type: "autogenerated", dirName: "spec" }],
  clientSdk: [{ type: "autogenerated", dirName: "client-sdk" }],
  serverSdk: [{ type: "autogenerated", dirName: "server-sdk" }],
};

export default sidebars;
